config/routes.rb
Running::Application.routes.draw do
  
  devise_for :users
  resources :places

  root to: 'welcome#index'
  get 'runs/records' => 'runs#records'
  resources :runs

  

end

app/models/place.rb
class Place < ActiveRecord::Base
    has_many :runs
    belongs_to :user

end

app/models/run.rb
class Run < ActiveRecord::Base

    belongs_to :place
    belongs_to :user

    def place_name
        if place
            place.name 
        else
            ""
        end
    end

    def duration_time
        if duration
            hours = duration / 3600
            minutes = (duration%3600)/60
            seconds = (duration%3600)%60
            "#{hours}:#{minutes}:#{seconds}"
        else
            ""
        end
    end

    def duration_time=(timestamp)
        array=timestamp.split(':')
        if array.length ==3
            hours=array[0].to_i
            minutes=array[1].to_i
            seconds=array[2].to_i
        elsif array.length == 2
            hours = 0
            minutes=array[0].to_i
            seconds=array[1].to_i
        end
        self.duration = 3600* hours + 60 * minutes + seconds    
    end

    def pace
        p=(duration/distance).to_i
        p_hours = p / 3600
        p_minutes = (p%3600)/60
        p_seconds = (p%3600)%60
        "#{p_hours}:#{p_minutes}:#{p_seconds}"
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :runs
    has_many :places
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name)
    end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_run, only: [:show, :edit, :update, :destroy]

  # GET /runs
  # GET /runs.json
  def index
    @runs=Run.where(:user_id => current_user.id).all.sort_by{|t| t[:date]}.reverse
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
  end

  def records
    @pace = Run.where(:user_id => current_user.id).all.sort_by{:pace}[0]
    @distance=Run.where(:user_id => current_user.id).all.sort_by{:distance}[0]
    @time=Run.where(:user_id => current_user.id).all.sort_by{:duration}[0]
    render 'records'
  end

  # GET /runs/new
  def new
    @run = Run.new
  end

  # GET /runs/1/edit
  def edit
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(run_params)
    @run.user=current_user

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render action: 'show', status: :created, location: @run }
      else
        format.html { render action: 'new' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    @run.user=current_user
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.where(:user_id => current_user.id).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:date, :duration_time, :distance, :description, :place_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Running</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="nav navbar-inverse" role="navigation">

  <div class="navbar-header">
    <a class="navbar-brand">Run</a>
  </div>

    <ul class="nav navbar-nav">
      <li class=<%= @home_active %>><%= link_to "Home", controller: "/welcome"%></li>
      <li class=<%= @profile_active %>><a href="#">My Profile</a></li>
      <li class=<%= @runs_active %>><%= link_to "My Runs", controller: "/runs" %></li>
      <li class=<%= @places_active %>><%= link_to "My Places", controller: "/places" %></li>
      <li class=<%= @records_active %>><%= link_to "Records", controller: "/runs", action: "records" %></li>
      <% if user_signed_in? %>
        <li>Signed in as <%= current_user.email %></li> 
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
        </li>
      <% else %>
        <li class="pull-right"><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
    </ul>


</nav>

<div class="container">

    <%= yield %>

</div>

<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<% @places_active = "active" %>
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<% @places_active = "active" %>
<h1>Listing places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<% @places_active = "active" %>
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<% @places_active = "active" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/runs/_form.html.erb
<%= form_for(@run) do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :duration_time %>
    <%= f.text_field :duration_time %>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.collection_select :place_id, Place.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runs/_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Date</th>
      <th>Distance</th>
      <th>Duration</th>
      <th>Pace</th>
      <th>Place</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @runs.each_with_index do |run, index| %>
      <tr>
        <td><%= index +1 %></td>
        <td><%= run.date %></td>
        <td><%= run.distance %></td>
        <td><%= run.duration_time %></td>
        <td><%= run.pace %></td>
        <td><%= run.place_name %></td>
        <td><%= link_to 'Show', run %></td>
        <td><%= link_to 'Edit', edit_run_path(run) %></td>
        <td><%= link_to 'Destroy', run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/runs/edit.html.erb
<% @runs_active = "active" %>
<h1>Editing run</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

app/views/runs/index.html.erb
<% @runs_active = "active" %>
<h1>Listing runs</h1>

<%= link_to 'New Run', new_run_path %>

<h2>By Date</h2>
<%= render 'table' %>

<h2>By Pace</h2>
<% @runs= @runs.sort_by{|p| p[:pace]}.reverse %>
<%= render 'table' %>

<h2>By Distance</h2>
<% @runs=@runs.sort_by{|d| d[:distance]}.reverse %>
<%= render 'table' %>

<br>


<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#home">Home</a></li>
  <li><a href="#profile">Profile</a></li>
  <li><a href="#messages">Messages</a></li>
  <li><a href="#settings">Settings</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="home">...</div>
  <div class="tab-pane" id="profile">profile</div>
  <div class="tab-pane" id="messages">messages</div>
  <div class="tab-pane" id="settings">settings</div>
</div>

app/views/runs/new.html.erb
<% @runs_active = "active" %>
<h1>New run</h1>

<%= render 'form' %>

<%= link_to 'Back', runs_path %>

app/views/runs/records.html.erb
<% @records_active = "active" %>
<h1>My Records!</h1>

<h2>Fastest Pace</h2>
<p><%= @pace.pace %></p>
<%= link_to 'Show', @pace %>

<h2>Longest Distance</h2>
<p><%= @distance.distance %></p>
<%= link_to 'Show', @distance %>

<h2>Longest Time</h2>
<p><%= @time.duration %></p>
<%= link_to 'Show', @distance %>

app/views/runs/show.html.erb
<% @runs_active = "active" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @run.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @run.duration_time %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @run.distance %>
</p>

<p>
  <strong>Description:</strong>
  <%= @run.description %>
</p>

<p>
  <strong>Place:</strong>
  <%= @run.place_name %>
</p>

<%= link_to 'Edit', edit_run_path(@run) %> |
<%= link_to 'Back', runs_path %>

app/views/welcome/index.html.erb
<% @home_active = "active" %>
<h1>Run Comparisons!</h1>